name: edumart_supplies
description: A school supplies business app for students, parents, schools, and vendors
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.2 # Updated from ^6.1.1 to ^6.1.2 as per your request
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  uuid: ^4.2.2
  flutter_svg: ^2.0.9
  image_picker: ^1.1.2 # Newly added

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
